# Generated by Django 3.2.25 on 2024-06-07 11:24

from django.db import migrations, models

def migrate_data(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        product.categories.add(product.category)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop.Category'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
